### ISSUE TITLE
Docker process killed when computing WER 

### ISSUE THREAD

**Issue by turchmo** [revdotcom/fstalign#25]
Dear Authors, 

thanks a lot for making available your code. 

I'm running the docker version of the software and I have some issues finalizing the computation of the WER on my test data. 

My hyp and ref files contain around 3k sentences for a total of 130k words. When I run the software, after processing 73000 words, the process is killed without any error message. I did not notice any particular RAM consumption on my machine. I'm not an expert in Docker, so I do not know if the issue is related to any Docker parameter. When working with a small portion of the data everything works fine.

I called the code in this way:
fstalign wer --output-sbs fstout/align.txt --ref fstout/ref.it.tok --hyp fstout/asr.it.tok  --log fstout/log.err   --disable-approx-alignment --disable-hyphen-ignore --disable-cutoffs

Please notice that without the --disable-approx-alignment flag the code crashed much earlier with the following error:
[+++] [09:42:11] [walker] starting a walk in the park
[+++] [09:42:11] [walker] we have 0 candidates after 45 loops
[+++] [09:42:11] [fstalign] done walking the graph
terminate called after throwing an instance of 'std::runtime_error'
  what():  no alignment produced
Aborted

Do you have suggestions on how to make the software process all the data?

Best regards,
Marco

**Comment by qmac** [comment]
Hi Marco! Thanks for opening an issue. These are quite large hyp and ref files for fstalign. If these are splittable into files or utterances, this would be advisable. Or if you could split the files up into 20k words chunks, that would also be helpful.

My guess as to what's happening is that the container is using all the RAM that docker has provisioned. For most operating systems I believe the default provision is 1GB of RAM (you would have to adjust the system preference to increase this). Based on what we found in this research: https://github.com/revdotcom/fstalign/wiki/fstalign-1.3.0-resource-benchmarking, this memory consumption will be exceeded using any "algorithm" of fstalign for files > 20k words.

Hopefully that helps!

**Comment by turchmo** [comment]
Hi Quinn,

Thanks a lot for your answers and tips, they are super useful! 

As a first step, I have simply increased the memory allocated to Docker in my Mac. If it does not work, I'll split the input files into pieces. 

I have an additional question (not related to this topic, if you prefer I can open a new issue with this question), is it possible to keep the true casing of the words when using the --output-sbs option? 

Thanks a lot!
Marco

**Comment by xanguera** [comment]
Hi @qmac I am getting the same problem as @turchmo . I am also a mac user, and I set docker enginer to use max 8GB of RAM, which should be more than enough.
I tested with 2 very short files, single line and only 100ish words, and I get the same problem:

[2022-03-31 10:06:50.904] [console] [info] loggers initialized
[+++] [10:06:50] [console] fstalign version is 1.5.0
[+++] [10:06:50] [console] reading reference plain text from /daily_transcripts/2022-03-29_daily/test_ref.txt
[+++] [10:06:50] [console] reading hypothesis plain text from /daily_transcripts/2022-03-29_daily/test_hyp.txt
[+++] [10:06:50] [fstalign] starting conversion to int vector
[+++] [10:06:50] [fstalign] converting ref to int vector
[+++] [10:06:50] [OneBestFstLoader] creating std::vector<int> for OneBestFstLoader for 140 tokens
[+++] [10:06:50] [fstalign] converting hyp to int vector
[+++] [10:06:50] [OneBestFstLoader] creating std::vector<int> for OneBestFstLoader for 109 tokens
[+++] [10:06:50] [fstalign] Estimated edit distance : 76 / 140 (46 edits originally)
[+++] [10:06:50] [fstalign] generating ref synonyms from symbol table
[+++] [10:06:50] [fstalign] applying ref synonyms on ref fst
[+++] [10:06:50] [SynonymEngine] we have 0 registered first word rules label id
[+++] [10:06:50] [fstalign] printing ref fst
[+++] [10:06:50] [fstalign] fst is too large to be printed on the console
[+++] [10:06:50] [fstalign] printing hyp fst
[+++] [10:06:50] [fstalign] fst is too large to be printed on the console
[+++] [10:06:50] [walker] starting a walk in the park
[+++] [10:06:50] [walker] we have 0 candidates after 1576 loops
[+++] [10:06:50] [fstalign] done walking the graph
terminate called after throwing an instance of 'std::runtime_error'
  what():  no alignment produced
Aborted

**Comment by qmac** [comment]
Hi @xanguera would you mind sharing the reference and hypothesis transcripts? This does look like a new bug.

**Comment by xanguera** [comment]
Sure, I am running the docker image as follows:
/fstalign/build/fstalign wer --ref /daily_transcripts/2022-03-29_daily/test_ref.txt --hyp /daily_transcripts/2022-03-29_daily/test_hyp.txt
[test_ref.txt](https://github.com/revdotcom/fstalign/files/8392635/test_ref.txt)
[test_hyp.txt](https://github.com/revdotcom/fstalign/files/8392636/test_hyp.txt)

Attaching sample files.

**Comment by qmac** [comment]
@xanguera Thank you for providing the file, this uncovered a bug, but the fix is easy to I'll open a quick PR for this case!

**Comment by qmac** [comment]
Feel free to test out the new image, `1.6.1`, which should have a fix for those files!
