### ISSUE TITLE
Rules containing wildcards

### ISSUE THREAD

**Issue by huangruizhe** [revdotcom/fstalign#36]
Hello, do you plan to enable wildcards in the file of custom synonyms?

For example:
```
[w]'s    |   [w] is
[w]'s    |   [w] has
```
where [w] can match any word. This is quite common, as [w] can be a person's or company's name.

**Comment by huangruizhe** [comment]
Another possible rule is:
```
[w1] [w2]    |   [w1][w2]
```
where the space between [w1] and [w2] is optional. For example, "touch tone" vs. "touchtone".
What do you think?

**Comment by nishchalb** [comment]
Hi, the synonym feature is intended to be conservative to avoid capturing things that don't make sense, e.g. for your example `sally's code` would be treated as equivalent to `sally is code`. 

But, if you would like to proceed with those examples, you could either:

- Iterate through your reference files and build a synonym list that has sufficient rules for them
- Use the [normalization feature](https://github.com/revdotcom/fstalign/blob/develop/docs/Advanced-Usage.md#normalizations), which gives you more fine grained control over where synonyms can apply

**Comment by huangruizhe** [comment]
Thanks for the suggestion! Yeah, that should also work.
