### ISSUE TITLE
Insertion error of entities

### ISSUE THREAD

**Issue by huangruizhe** [revdotcom/fstalign#37]
Hi, I was wondering in the calculation of entity WER, will there be insertion errors?

Since we only have entity tagging for the reference text, there can be deletion and subsitution errors for the entities in the reference.
However, if there is an insertion error in the hypothesis, the tool does not know whether it is an entity or not.
So the insertion error for the entities is always zero. Is that true? Thanks!

**Comment by qmac** [comment]
Hi!

There can still be insertions during entities tagged in the reference. For example:
Ref: the population is [four hundred and five million](CARDINAL)
Hyp: the population is four hundred and uh five million

Here "uh" is counted as an insertion in the entity, at least how we define it and implemented here.

**Comment by qmac** [comment]
But you are right, if there's an entity on the hypothesis we don't have a mechanism to detect/flag it.

**Comment by migueljette** [comment]
@huangruizhe -- Good question and observation! 
I am wondering ... is there a case where we care about this information? I guess it's interesting to know if your system has a tendency to insert specific words or if it only inserts "unimportant words" (like uh/um), and so on. It would require tagging the hypothesis, which is not impossible I guess, right?
@qmac if the hypothesis were tagged, would fstalign be able to use the info to produce stats?

**Comment by qmac** [comment]
> @qmac if the hypothesis were tagged, would fstalign be able to use the info to produce stats?

Not really right now, we'd have to find a way to code it in

**Comment by huangruizhe** [comment]
Sorry, the notification on my side seems turned off!

@qmac Thanks for your explanation. And the example also makes a lot of sense.

@migueljette I was actually comparing the entity WER computed by fstalign vs. my script. Besides, I saw in other [repo](https://github.com/facebookresearch/fbai-speech/blob/main/is21_deep_bias/score.py#L279) that people seemed to have also considered the errors on the hyp side.
So it seems to me that the metric is not yet standardized when it comes to "entity WER". That's where my previous confusion came from.
